// Copyright Alec Greene. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace WeaponsTags
{
	WEAPONS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Hit);

	WEAPONS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot);
	WEAPONS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Arm_Left);
	WEAPONS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Arm_Right);
	WEAPONS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Hand_Left);
	WEAPONS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Hand_Right);

	WEAPONS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attack);
}